### ISSUE TITLE
class_name.py throws TypeError

### ISSUE THREAD

**Issue by HarmenJorritsma** [pydantic/FastUI#82]
Hi, 

Interesting library! I am a newby and tried a hello-world app, with the default code.  I run the code in a Docker container on Python 3.9. I get this TypeError: 

File "/usr/local/lib/python3.9/site-packages/fastui/class_name.py", line 6, in <module>
    ClassName = Annotated[str | list[str] | dict[str, bool | None] | None, Field(serialization_alias='className')]
TypeError: unsupported operand type(s) for |: 'type' and 'types.GenericAlias'

Any suggestions?

Kind regards, Harmen

**Comment by hasansezertasan** [comment]
It's an incompatibility issue with the new syntax for `Union`. I believe `|` doesn't work on 3.9, it's fixed in #66

**Comment by HarmenJorritsma** [comment]
Thanks. I tried running fastUI with Python 3.10 instead of 3.9 and I tried with the latest fastUI via github.  Both doesn't solve the TypeError. I will wait for the next release.

**Comment by samuelcolvin** [comment]
I'll do a release soon, to use the current release, you need 3.11.

**Comment by samuelcolvin** [comment]
this is fixed since I released v0.3.0 yeseterday.
